### ISSUE TITLE
link checker maxing CPU

### ISSUE THREAD

**Issue by lppdev** [ocodia/Check-My-Links#39]
Hi,

I have run link checker on a site on my server and each time it maxes out my server's CPU - any advice?

Thanks!

**Comment by ocodia** [comment]
The link checker is essentially loading all of the links in order to check their HTTP status. So it will increase demand on your web server... but this should subside after the check has finished. If your server's CPU is still maxed out long after the check has finished, then I'm afraid there's something wrong with the code being executed by your server.
