### ISSUE TITLE
3 issues - different results every time - can't see broken link info - and not crawling the whole site

### ISSUE THREAD

**Issue by pinkflamingoTX** [ocodia/Check-My-Links#74]
Hi I have three issues. 

1) first every time i RUN the app it shows a DIFFERENT result, on the SAME webpage (here are two screen shots included). so clearly something is wrong. how can i get different data, seconds apart, on the same webpage?

2) when i do get "invalid link" errors, there is no way for me to SEE the actual information (ie what page the link is on and which link is broken). Am i missing something? I tried the export top right button but nothing happens.

3) finally, I have WAY more than the 200 or so links that this extension finds...there should be 1,000 or more links on the whole site. so again, somethign is wrong. If i start on the HOME PAGE, it should crawl the ENTIRE site, correct?

Would love for this extension to work, so any help is much appreciated! thank you

![href results - 2](https://user-images.githubusercontent.com/28063068/30358863-0956e36c-97fc-11e7-8f6c-84dc6ea9f3b7.PNG)
![href results - 3](https://user-images.githubusercontent.com/28063068/30358862-0951fe1a-97fc-11e7-9e83-2576166e858d.PNG)

**Comment by ocodia** [comment]
Hi.

1. Which page are you running the checker on? If you can let me know I can test it and see what the problem is.

2. HTTP response codes and the full URLs of broken links are published in the Console log (Found in: 'Chrome > Tools > Javascript Console' or Ctrl+Shift+J). Documentation is [here](https://github.com/ocodia/Check-My-Links/wiki).

3. Your assumption is incorrect, I'm afraid. The extension can only check the links of the page you are currently viewing. To do site-wide checks, try [XENU Link Sleuth](http://home.snafu.de/tilman/xenulink.html) - which is free btw - or you can pay for a site-wide link checking service from one of the many companies that provide such a thing.

Hope that helps.

**Comment by pinkflamingoTX** [comment]
Thanks so much for the quick response! But the answer to 3 then makes my questions for 1 and 2 moot :) I have used XENU Link Sleuth before, but would prefer a chrome plugin instead of their download.

Thanks again for clarifying my issues. Really appreciate it.

**Comment by ocodia** [comment]
No worries!
