### ISSUE TITLE
Malwarebytes Issue

### ISSUE THREAD

**Issue by semperaye** [ocodia/Check-My-Links#85]
Malwarebytes is now flagging this as outbound malware.

**Comment by ocodia** [comment]
On what justification? I publish the source code, the code of the bundled extension can be un-packed and read... I've had repeated offers to include adware and other such "money making opportunities" which I have repeatedly rejected. On what grounds is this "outbound malware", exactly?

**Comment by semperaye** [comment]
I think it might have been one of the urls i was scanning was malware? It hasn't happened again.

**Comment by ocodia** [comment]
That makes more sense. The URLs that the extension validates need to be requested and loaded in order to determine their validity. If the extension is asked to validate a URL that points to malware, it will try to. If you want to blacklist URLs you can do so in the extension settings. Closing this issue as it is expected behaviour.
