### ISSUE TITLE
Could Not Mark 404/Broken Links

### ISSUE THREAD

**Issue by sawsmithgit** [ocodia/Check-My-Links#88]
Hey,
Suddenly I notice, My Check My Links Chrome Extention could not identify 404 properly. Sometimes it misses some links and marks it green instead of red.

**Comment by ThomasMeisel** [comment]
I've noticed the same. I've tried out to use _Check my links_ but isn't trustworthy enough.  :(
For example the link _<a href="https://www.getpostman.com/test" target="_blank">Postman</a>_ is marked as valid but is a 404.

**Comment by ocodia** [comment]
That's because when you try to check that Postman URL, the server returns an HTTP 302 (Moved temporarily) which IS a valid (green) link. Even though the page says "404 page not found" doesn't mean the server officially responded that way. 

`HTTP Response Header https://www.getpostman.com/test

HTTP/2 302
content-type: application/xml
location: https://www.getpostman.com/test/
date: Thu, 16 Aug 2018 12:54:48 GMT
server: AmazonS3
strict-transport-security: max-age=300; includeSubDomains
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
age: 90
x-cache: Hit from cloudfront
via: 1.1 5b7194cd796490b3bb20e0ed10b59026.cloudfront.net (CloudFront)
x-amz-cf-id: euaI4O5oDnRMqI1iZqxEWjoxdFb7x7POzJwsem93H1RQDdSVLU_oFg==`
